name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "7056de3d52ec4db3984b6c10c0b1f2f4" },
  { binding = "SHARE", id = "84f65fb0e96641709528bbd4aa8cd0e4" }
]