name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "SCN-notes", id = "31c64baa6b974203a20c4171bced3b97" },
  { binding = "SCN-share", id = "c3d33e81cda3425d9bd09beb312e6891" }
]
